import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faClipboard,
  faUser,
  faEnvelope,
  faBuilding,
  faIdCard,
  faSun,
  faLifeRing,
  faTrashCan,
  faCirclePlay,
  faCirclePause,
  faBell,
  faMoon,
  faClock,
} from '@fortawesome/free-regular-svg-icons';
import {
  faPowerOff,
  faChevronDown,
  faFilter,
  faClose,
  faBars,
  faArrowLeft,
  faUserTie,
  faLocationDot,
  faCaretUp,
  faCaretDown,
} from '@fortawesome/free-solid-svg-icons';
import { faGoogle } from '@fortawesome/free-brands-svg-icons';

library.add(
  faClipboard,
  faGoogle,
  faUser,
  faEnvelope,
  faIdCard,
  faBuilding,
  faSun,
  faLifeRing,
  faPowerOff,
  faChevronDown,
  faFilter,
  faClose,
  faBars,
  faTrashCan,
  faArrowLeft,
  faCirclePlay,
  faCirclePause,
  faUserTie,
  faBell,
  faMoon,
  faClock,
  faLocationDot,
  faCaretUp,
  faCaretDown
);
