name: CI

on: push
jobs:
  lint-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14.x, 16.x]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install deps
        run: |
          npm install
      - name: Run lint
        run: |
          npm run lint
      - name: Run prettier
        run: |
          npm run format
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14.x, 16.x]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install deps
        run: |
          npm install
      - name: Run test
        run: |
          npm run test
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14.x, 16.x]
    needs: [lint-format, test]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install deps
        run: |
          npm install
      - name: Run build
        run: |
          npm run build
